[package]
name = "yew-app"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]
edition = "2018"

[dependencies]
log = "0.4"
web_logger = "0.2"
yew = {git = "https://github.com/yewstack/yew", branch = "master"}
